from typing import Optional


class ContentSettings:
    content_type: str = ...
    content_encoding: str = ...
    content_language: str = ...
    content_md5: str = ...
    content_disposition: str = ...
    cache_control: str = ...

    def __init__(self,
                 content_type: Optional[str] = ...,
                 content_encoding: Optional[str] = ...,
                 content_language: Optional[str] = ...,
                 content_disposition: Optional[str] = ...,
                 cache_control: Optional[str] = ...,
                 content_md5: Optional[str] = ...,
                 **kwargs: str) -> None:
        ...
